// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7TqBQsvD2hgcWMKEGOKPP7a8ptEGy0-o',
    appId: '1:837308570802:android:c0c94fefcee16c0188bdab',
    messagingSenderId: '837308570802',
    projectId: 'sensink-appdev',
    databaseURL: 'https://sensink-appdev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensink-appdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWKIJdQW1M4zGqHX59XqU6U6O4KAajCbU',
    appId: '1:837308570802:ios:0a0d7900f19ea74688bdab',
    messagingSenderId: '837308570802',
    projectId: 'sensink-appdev',
    databaseURL: 'https://sensink-appdev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensink-appdev.firebasestorage.app',
    androidClientId: '837308570802-0afc78t16r5f59b73864ui5eljpct6j6.apps.googleusercontent.com',
    iosClientId: '837308570802-mq4ult79vmvit8l37nvjh3b5d166jcep.apps.googleusercontent.com',
    iosBundleId: 'com.example.sensinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo4Ourmg3uZ1ZOD7Ns2od8jajSBrVWhCU',
    appId: '1:837308570802:web:408bf2c33307469788bdab',
    messagingSenderId: '837308570802',
    projectId: 'sensink-appdev',
    authDomain: 'sensink-appdev.firebaseapp.com',
    databaseURL: 'https://sensink-appdev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensink-appdev.firebasestorage.app',
    measurementId: 'G-H8G6SRMHZH',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo4Ourmg3uZ1ZOD7Ns2od8jajSBrVWhCU',
    appId: '1:837308570802:web:408bf2c33307469788bdab',
    messagingSenderId: '837308570802',
    projectId: 'sensink-appdev',
    authDomain: 'sensink-appdev.firebaseapp.com',
    databaseURL: 'https://sensink-appdev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sensink-appdev.firebasestorage.app',
    measurementId: 'G-H8G6SRMHZH',
  );

}